version: '3.3'
services:
   web:
    container_name: web
    image: web
    build: "$PWD"
    ports:
      - "82:80"
    volumes:
       - "$PWD/volapp/web:/usr/share/nginx/html"
    networks:
      - net
   jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
    volumes:
      - "$PWD/volapp/jenkins_home:/var/jenkins_home"
    networks:
      - net
   nessus:
    container_name: nessus
    image: tenable/nessus:latest-ubuntu
    ports:
      - "8834:8834"
    volumes:
      - datos_nessus:/opt/nessus/var/nessus
    networks:
      - net
networks:
  net:
volumes:
  datos_nessus:
